# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Projects' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  pod 'SVProgressHUD'
  pod 'ImageViewer'
  pod 'ParallaxHeader', '~> 2.0.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'RealmSwift', '>= 0.92.3', :modular_headers => true
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for Projects

  target 'ProjectsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
